### ISSUE TITLE
when your paper and code will be published?

### ISSUE THREAD

**Issue by xzb666** [CUHK-AIM-Group/CLIFF#1]
Hello, may I ask when your paper and code will be published? I would like to read them. Thank you very much

**Comment by wymanCV** [comment]
Hi, @xzb666,

Thank you so much for your interest in our work! Thank you for your attention to our previous work, SIGMA! The code and paper have been released. If you have any questions or need further discussion, feel free to reach out to me via email at [wymanbest@outlook.com](mailto:wymanbest@outlook.com).

Best regards,
Wuyang
